AdoptionLab/AdoptionLab/Models/Data/AppDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace AdoptionLab.Models.Data
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

        public DbSet<Pet> Pets { get; set; }
    }
}

AdoptionLab/AdoptionLab/Models/ErrorViewModel.cs
namespace AdoptionLab.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AdoptionLab/AdoptionLab/Models/Pet.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdoptionLab.Models
{
    public class Pet
    {
        public int Id { get; set; }

        [Required]
        public int Age { get; set; }

        [Column(TypeName ="varchar(20)")]
        [Required]
        public string Name { get; set; }

        [Column(TypeName = "varchar(20)")]
        [Required]
        public string Species { get; set; }

        [Column(TypeName = "varchar(20)")]
        [Required]
        public string Breed { get; set; }


        [Column(TypeName = "text")]
        [Required]
        public string Description { get; set; }

        [Column(TypeName = "nvarchar(MAX)")]
        [Required]
        public string Image{ get; set; }

    }
}

AdoptionLab/AdoptionLab/Controllers/HomeController.cs
using AdoptionLab.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdoptionLab.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AdoptionLab/AdoptionLab/Controllers/PetController.cs
using AdoptionLab.Models;
using AdoptionLab.Models.Data;
using Microsoft.AspNetCore.Mvc;

namespace AdoptionLab.Controllers
{
    public class PetController : Controller
    {
        //Dependency injection
        private readonly AppDbContext _appDbContext;

        //we are injecting the DbContect into this controller through the constructor
        public PetController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }
        public IActionResult Index(string? searchTerm)
        {

            if(searchTerm != null)
            {
                return View(_appDbContext.Pets.Where(x => x.Species.ToLower().Trim().Contains(searchTerm.ToLower().Trim())).ToList());
            }

            List<Pet> pets = _appDbContext.Pets.ToList();
            return View(pets);
        }

        public IActionResult GetById(int id)
        {
            Pet pet = _appDbContext.Pets.FirstOrDefault(x => x.Id == id);

            if(pet == null)
            {
                return NotFound();
            }
            return View(pet);
        }

        public IActionResult Delete(int id)
        {
            Pet pet = _appDbContext.Pets.FirstOrDefault(x => x.Id == id);
            if (pet != null)
            {
                _appDbContext.Pets.Remove(pet);
                _appDbContext.SaveChanges();
                return RedirectToAction("Confirmation");
            }
            return NotFound();
        }

        public IActionResult Confirmation()
        {
            return View();
        }

        public IActionResult Adopt()
        {
            Pet pet = new Pet();
            return View(pet);
        }

        [HttpPost]
        public IActionResult ProcessPetForm([FromForm] Pet newPet)
        {

            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            //db context then table then add and finally what we are adding
            _appDbContext.Pets.Add(newPet);

            //this step is easy to forget
            //this is where it is actually saved to the database. If you dont do this it wont be saved
            _appDbContext.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

AdoptionLab/AdoptionLab/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<a asp-action="Index" asp-controller="Pet">See pets</a>
<a asp-action="Adopt" asp-controller="Pet">Add pets</a>

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AdoptionLab/AdoptionLab/Views/Pet/Adopt.cshtml
@model Pet

<form method="post" action="/Pet/ProcessPetForm">
    <div class="form-group">
        <label asp-for="Name">Pet's Name</label>
        <input asp-for="Name" class="form-control" required />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Age">Pet's Age</label>
        <input asp-for="Age" class="form-control" required />
        <span asp-validation-for="Age" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Species">Pet's Species</label>
        <input asp-for="Species" class="form-control" required />
        <span asp-validation-for="Species" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Breed">Pet's Breed</label>
        <input asp-for="Breed" class="form-control" required />
        <span asp-validation-for="Breed" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Pet's Description</label>
        <input asp-for="Description" class="form-control" required />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image">Pet's Picture</label>
        <input asp-for="Image" class="form-control" required />
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    <button type="submit">Submit</button>
</form>

AdoptionLab/AdoptionLab/Views/Pet/Confirmation.cshtml
<div class="text-center">
    <h1> Congratulations! On finding your new Fuzzy Friend!</h1>
    <a class="btn btn-primary" asp-action="Index" asp-controller="Pet">Back</a>
    <a class="btn btn-primary" asp-action="Index" asp-controller="Home">Home</a>
</div>

AdoptionLab/AdoptionLab/Views/Pet/GetById.cshtml
@model Pet

<a class="btn btn-primary" asp-action="Index" asp-controller="Home">Home</a>
<div class="text-center">
    <h1>@Model.Name - @Model.Age</h1>
    <img src="@Model.Image" style="width: 300px; height: 300px"/>
    <p>@Model.Species</p>
    <p>@Model.Breed</p>
    <p>@Model.Description</p>
    <div class="buttonContainer">
        <a class="btn btn-primary" asp-action="Delete" asp-controller="Pet" asp-route-id=@Model.Id>Adopt</a>
        <a class="btn btn-primary" asp-action="Index" asp-controller="Pet">Back</a>
    </div>
</div>

AdoptionLab/AdoptionLab/Views/Pet/Index.cshtml
@model List<Pet>


<a class="btn btn-primary" asp-action="Index" asp-controller="Home">Home</a>
<div class="text-center">
    <h1>Welcome to FuzzyFriends Pet Adoption!</h1>

    <div class="row">
        <div class="text-center">
            <form asp-controller="Pet" asp-action="Index">
                <div class="input-group mb-3">
                    <input name="searchTerm" type="text" class="form-control" placeholder="Search" aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <button type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        @foreach(var pet in Model)
        {
            <div class="col-3">
                <div class="card" style="width: 18rem;">
                    <img src="@pet.Image" class="card-img-top" alt="@pet.Name">
                    <div class="card-body">
                        <h5 class="card-title">@pet.Name</h5>
                        <p class="card-text">@pet.Description</p>
                        <a class="btn btn-primary" asp-action="GetById" asp-controller="Pet" asp-route-id=@pet.Id>Details</a>
                    </div>
                </div>
            </div> 
        }
    </div>
</div>

AdoptionLab/AdoptionLab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdoptionLab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdoptionLab.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AdoptionLab</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AdoptionLab - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>